name: test

on: [push, pull_request, release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Postgresql with Postgis
      uses: ireznik/postgis-action@v12
      with:
        postgresql user: 'test'
        postgresql password: 'test'
        postgresql db: 'test'

    - uses: jiro4989/setup-nim-action@v1.3.4
        
    - name: Run test
      run: nim c -r tests/connection.nim
      env:
        password: 'test'